### ISSUE TITLE
Throw Exception

### ISSUE THREAD

**Issue by chenxiaochun** [qawemlilo/prompt#2]
Age (invalid): events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: shutdown EPIPE
    at exports._errnoException (util.js:746:11)
    at Socket.onSocketFinish (net.js:240:26)
    at Socket.emit (events.js:104:17)
    at finishMaybe (_stream_writable.js:484:14)
    at endWritable (_stream_writable.js:493:3)
    at Socket.Writable.end (_stream_writable.js:459:5)
    at Socket.end (net.js:415:31)
    at ask (D:\MyProject\Test\node_modules\simple-prompt\lib\prompt.js:156:24)
    at D:\MyProject\Test\node_modules\simple-prompt\lib\prompt.js:224:17
    at Socket.<anonymous> (D:\MyProject\Test\node_modules\simple-prompt\lib\prompt.js:137:17)

**Comment by qawemlilo** [comment]
@chenxiaochun thanks, will update the package.
